@include('pages.frontend.includes.headtags')
@include('pages.frontend.includes.header')
@include('pages.frontend.includes.footer')
@include('pages.frontend.includes.endtags')

@yield('headtags')
@yield('header')
@yield('content')
@yield('footer')
@yield('endtags')